version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-wordpress
    ports:
    - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_DATABASE: wordpress
      WORDPRESS_SITE_URL: "localhost:8080"
      WORDPRESS_SITE_DESCRIPTION: "This is where it all happens"
    volumes:
    - ./data:/var/www/html


  mysql:
    image: mysql:5.7
    volumes:
    - ./db_data:/var/lib/mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress