version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-wordpress
    ports:
    - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp333_"
      WORDPRESS_SITE_URL: "localhost:8080"
      WORDPRESS_SITE_DESCRIPTION: "This is where it all happens"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: "/* Extra settings to change when deploying */\ndefine('FORCE_SSL_ADMIN', false);\ndefine('DISALLOW_FILE_MODS', false);\ndefine('DISALLOW_FILE_EDIT', false);\ndefine('WP_HOME','http://localhost:8080');\ndefine('WP_SITEURL','http://localhost:8080');"
    volumes:
    - ./data:/var/www/html


  mysql:
    image: mysql:5.7
    volumes:
    - ./db_data:/var/lib/mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
